---
--- CREATE DATABASE: financas
---
CREATE DATABASE IF NOT EXISTS financas;
--
-- CREATE TABLE: Usuario
--
CREATE TABLE IF NOT EXISTS financas.Usuario
(
	ID_USUARIO INTEGER NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(40) NOT NULL,
	STATUS CHAR NOT NULL,
	APELIDO VARCHAR(20) NOT NULL,
	SENHA VARCHAR(20) NOT NULL,
	CONSTRAINT PRIMARY KEY (ID_USUARIO)
)
	ENGINE = InnoDB;
--
-- CREATE TABLE: Aplicacao
--
CREATE TABLE IF NOT EXISTS financas.Aplicacao
(
	NOME_RECURSO VARCHAR(40) NOT NULL,
	NOME VARCHAR(20) NOT NULL,
	DESCRICAO VARCHAR(40) NOT NULL,
	CONSTRAINT PRIMARY KEY (NOME_RECURSO)
)
	ENGINE = InnoDB;
--
-- CREATE TABLE: Acesso
--
CREATE TABLE IF NOT EXISTS financas.Acesso
(
	ID_USUARIO INTEGER NOT NULL,
	NOME_RECURSO VARCHAR(40) NOT NULL,
	CONSULTA CHAR,
	ALTERA CHAR,
	INCLUI CHAR,
	EXCLUI CHAR,
	CONSTRAINT PRIMARY KEY (ID_USUARIO, NOME_RECURSO)
)
	ENGINE = InnoDB;

--
-- CREATE FOREIGN KEY CONSTRAINT: Relation_1
--
ALTER TABLE financas.Acesso ADD 
	FOREIGN KEY (ID_USUARIO)
		REFERENCES financas.Usuario (ID_USUARIO);


--
-- CREATE FOREIGN KEY CONSTRAINT: Relation_2
--
ALTER TABLE financas.Acesso ADD 
	FOREIGN KEY (NOME_RECURSO)
		REFERENCES financas.Aplicacao (NOME_RECURSO);

--
-- CREATE TABLE: Contato
--
CREATE TABLE IF NOT EXISTS financas.Contato
(
	ID_CONTATO INTEGER(5) NOT NULL,
	NOME VARCHAR(40) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	SEXO CHAR NOT NULL,
	ENDERECO VARCHAR(30),
	COMPLEMENTO VARCHAR(20),
	BAIRRO VARCHAR(30),
	CEP VARCHAR(9),
	TELEFONE_FIXO VARCHAR(20),
	TELEFONE_CELULAR VARCHAR(20),
	EMAIL VARCHAR(20),
	CONSTRAINT PRIMARY KEY (ID_CONTATO)
)
	ENGINE = InnoDB;
--
-- CREATE TABLE: Compromisso
--
CREATE TABLE IF NOT EXISTS financas.Compromisso
(
	ID_COMPROMISSO INTEGER(5) NOT NULL AUTO_INCREMENT,
	DATA_HORA_INICIO DATETIME NOT NULL,
	DATA_HORA_FINAL DATETIME,
	ASSUNTO VARCHAR(20) NOT NULL,
	OBSERVACOES VARCHAR(30),
	ID_CONTATO INTEGER(5),
	CONSTRAINT PRIMARY KEY (ID_COMPROMISSO)
)
	ENGINE = InnoDB;

--
-- CREATE FOREIGN KEY CONSTRAINT: Relation_1
--
ALTER TABLE financas.Compromisso ADD 
	FOREIGN KEY (ID_CONTATO)
		REFERENCES financas.Contato (ID_CONTATO);

--
-- CREATE TABLE: Conta
--
CREATE TABLE IF NOT EXISTS financas.Conta
(
	ID_CONTA INTEGER NOT NULL AUTO_INCREMENT,
	ID_USUARIO INTEGER NOT NULL,
	NOME_CONTA VARCHAR(20) NOT NULL,
	DESCRICAO VARCHAR(30) NOT NULL,
	DATA_CRIACAO DATE NOT NULL,
	CONSTRAINT PRIMARY KEY (ID_CONTA, ID_USUARIO)
)
	ENGINE = InnoDB;

--
-- CREATE FOREIGN KEY CONSTRAINT: Relation_1
--
ALTER TABLE financas.Conta ADD 
	FOREIGN KEY (ID_USUARIO)
		REFERENCES financas.Usuario (ID_USUARIO);

--
-- CREATE TABLE: Categoria
--
CREATE TABLE IF NOT EXISTS financas.Categoria
(
	ID_CATEGORIA INTEGER NOT NULL AUTO_INCREMENT,
	NOME_CATEGORIA VARCHAR(20) NOT NULL,
	CONSTRAINT PRIMARY KEY (ID_CATEGORIA)
)
	ENGINE = InnoDB;
--
-- CREATE TABLE: Movimento
--
CREATE TABLE IF NOT EXISTS financas.Movimento
(
	ID_MOVIMENTO INTEGER NOT NULL AUTO_INCREMENT,
	ID_CATEGORIA INTEGER NOT NULL,
	ID_CONTA INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	DATA DATE NOT NULL,
	HISTORICO VARCHAR(20) NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	CONSTRAINT PRIMARY KEY (ID_MOVIMENTO, ID_CATEGORIA, ID_CONTA, ID_USUARIO)
)
	ENGINE = InnoDB;

--
-- CREATE FOREIGN KEY CONSTRAINT: Relation_2
--
ALTER TABLE financas.Movimento ADD 
	FOREIGN KEY (ID_CATEGORIA)
		REFERENCES financas.Categoria (ID_CATEGORIA);


--
-- CREATE FOREIGN KEY CONSTRAINT: Relation_1
--
ALTER TABLE financas.Movimento ADD 
	FOREIGN KEY (ID_CONTA, ID_USUARIO)
		REFERENCES financas.Conta (ID_CONTA, ID_USUARIO);

